config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show, :edit, :update] do
    resources :reviews, only: [:index]
    resources :purchases, only: [:index]
  end

  resources :vinyls do
    member do
      get "order", to: "vinyls#order"
    end
    resources :purchases, only: [:create]
  end
  # get "users/:id/reviews", to: "reviews#index"
  resources :purchases, only: [:show] do
    resources :reviews, only: [:show, :new, :create]
  end

  resources :users, only: [:show] do
    member do
      get "vinyls", to: "users#show_vinyls"
      # get "vinyls", to: ""
    end
  end
  # delete "vinyls/:id", to: "vinyls#destroy"

  # I was trying out some stuff for marking vinyls as sold, please keep it.
  # resources :users, only: [:show] do
  #   member do
  #     get "vinyls/:id", to: "vinyls#mark_as_sold"
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern
  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :vinyl
  belongs_to :user, :foreign_key => 'buyer_id', class_name: "User"
  has_one :review
  validates :name, presence: true
  validates :house_number, presence: true
  validates :street_name, presence: true
  validates :post_code, presence: true
  validates :city, presence: true
  validates :card_holder, presence: true
  validates :card_number, presence: true, format: { with: /\d{4}\s?\d{4}\s?\d{4}\s?\d{4}\z/ }
  validates :expiry_date, presence: true
  validates :security_code, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :purchase
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vinyls, :foreign_key => 'seller_id', class_name: "Vinyl"
  has_many :sells, through: :vinyls, :foreign_key => 'vinyl_id', source: :purchase
  has_many :reviews, through: :sells, source: :review
  has_many :purchases, :foreign_key => 'buyer_id', class_name: "Purchase"
  mount_uploader :photo, PhotoUploader


end

app/models/vinyl.rb
class Vinyl < ApplicationRecord
  include Filterable

  scope :named, -> (named) { where("name ILIKE ?", "%#{named}%") }
  scope :artist, -> (artist) { where("artist ILIKE ?", "%#{artist}%") }
  scope :genre, -> (genre) { where(genre: genre) }
  scope :min_price, -> (min_price) { where("price > ?", "#{min_price}") }
  scope :max_price, -> (max_price) { where("price < ?", "#{max_price}") }
  belongs_to :seller, :foreign_key => 'seller_id', class_name: "User"
  has_one :purchase
  mount_uploader :photo, PhotoUploader
  validates :media_link, format: { with: /.*:album:.*|/ , message: "must be a Spotify Album URI" }
  validates :price, presence: true

  def sold?
    !purchase.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :address, :first_name, :last_name])
  end

  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @vinyls = Vinyl.limit(6).order(created_at: :desc)
    # test
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @purchases = policy_scope(Purchase).where(buyer_id: params[:user_id])
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @vinyl = Vinyl.find(params[:vinyl_id])
    @purchase.vinyl = @vinyl
    @purchase.buyer_id = current_user.id
    @vinyl.sold = true
    if @purchase.save!
      authorize @purchase
      redirect_to purchase_path(@purchase)
    else
      redirect_to vinyls_path
    end
    # @purchase.save
  end

  def show
    @purchase = Purchase.find(params[:id])
    authorize @purchase
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :house_number, :street_name, :post_code, :city, :card_holder, :card_number, :expiry_date, :security_code, :buyer_id, :vinyl_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_purchase, only: [:new, :create]
  skip_after_action :verify_policy_scoped, only: :index
  def index
    @user = User.find(params[:user_id])
    @reviews = @user.reviews
    authorize @reviews
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.purchase = @purchase
    authorize @review
    if @review.save!
      redirect_to purchase_review_path(@purchase, @review)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
    authorize @review
  end

  private

  def find_purchase
    @purchase = Purchase.find(params[:purchase_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit]
  def show
  end

  def edit
    authorize @user
  end

  def update
    @user = current_user
    @user.update(vinyl_params)
    if @user.save
      authorize @user
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show_vinyls
    @user = current_user
    authorize @user
    @user.vinyls.order(created_at: :desc)
    # @user.vinyl = Vinyl.find(params[:vinyl_id])
  end

    private

  def find_user
    @user = User.find(params[:id])
    authorize @user
  end

  def vinyl_params
    params.require(:user).permit(:email, :address, :first_name, :last_name, :photo)
  end
end

app/controllers/vinyls_controller.rb
class VinylsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_vinyl, only: [:show, :edit, :destroy, :update, :order]

  def index
    @vinyls = policy_scope(Vinyl).filter(params.slice(:genre, :artist, :named, :min_price, :max_price)).order(created_at: :desc)
#     @vinyls = policy_scope(Vinyl).order(created_at: :desc)
#     # add this line if you want to have a seperate index
#     # for each individual user: .where(user: current_user)
#     if params[:query].present?
#       sql_query = "name ILIKE :query OR artist ILIKE :query OR description ILIKE :query"
#       @vinyls = Vinyl.where(sql_query, query: "%#{params[:query]}%")
#     else
#       @vinyls = Vinyl.where(sold: false)
#     end
#   end

#   def show
#   end

  end

  def show
    @user_vinyls = Vinyl.where(sold: false).where(seller: @vinyl.seller).order(created_at: :desc)
  end

  def new
    @vinyl = Vinyl.new
    authorize @vinyl
  end

  def create
    @vinyl = Vinyl.new(vinyl_params)
    @vinyl.seller = current_user
    authorize @vinyl
    if @vinyl.save
      redirect_to vinyl_path(@vinyl)
    else
      render :new
    end
  end

  def edit
    authorize @vinyl
  end

  def order
    # @purchase = Purchase.new
    @purchase = Purchase.new
  end

  def update
    @vinyl.update(vinyl_params)
    if @vinyl.save
      redirect_to vinyl_path(@vinyl)
    else
      render :edit
    end
  end

  def destroy
    @vinyl.destroy
    redirect_to vinyls_user_path(current_user)
  end

  private

  def find_vinyl
    @vinyl = Vinyl.find(params[:id])
    authorize @vinyl
  end

  def vinyl_params
    params.require(:vinyl).permit(:name, :genre, :price, :artist, :year, :description,
      :condition, :photo, :seller_id, :media_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('logo.ico') %>
    <title>True Vinyl</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="min-height: calc(100vh - 205px)">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="container" style="margin-top: 10px; margin-bottom: 20px">
  <br>

  <br>
  <h2 style= "text-align: center;">Get inspired by latest records on sale</h2>
  <br>

  <div class="cards">
    <% @vinyls.each do |vinyl| %>
    <% next if vinyl.sold? %>
      <%= link_to vinyl_path(vinyl) do %>
        <div class="card-full">
          <div class="card-full-infos">
            <div>
              <h2><%= vinyl.name %></h2>
              <p><%= vinyl.artist %></p>
            </div>
            <h2 class="card-full-pricing">£ <%= vinyl.price %></h2>
          </div>
            <%= cl_image_tag vinyl.photo %>
        </div>
      <% end %>
    <% end %>
  </div>
  <br>
  <div style= "text-align: center;">
    <%= link_to "Browse all", vinyls_path(@vinyl), class: 'btn btn-flat', style: 'color:white;'%>
  </div>
</div>

</div>

app/views/purchases/index.html.erb
<div class="container" style="margin-top: 70px">
<h1 class="text-center">Your Recent Purchases</h1>
  <div class= "d-flex p-4 bg-light border-bottom align-items-center justify-content-between m-3">
    <div>
      <% @purchases.each do |purchase| %>
        <h2><%= cl_image_tag purchase.vinyl.photo, height: 150, width: 150, crop: :fill %></h2>
        <%= link_to "Review Purchase", new_purchase_review_path(purchase), class: "btn btn-primary" %>
        <h2> Purchase ID Number: <strong><%= purchase.id %></h2></strong>
        <h2> Vinyl Name: <strong><%= purchase.vinyl.name %></h2></strong>
        <h2> Seller Name: <strong><%= purchase.vinyl.seller.first_name %> <%= purchase.vinyl.seller.last_name %> </h2></strong>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/purchases/show.html.erb
  <h1 class="text-center">Thank you for your order</h1>
  <div class="container">
    <div class= "d-flex p-4 bg-light border-bottom align-items-center justify-content-between m-3">
      <div>
        <h2>Order Number: <%= @purchase.id %></h2>
        <hr>
        <p>We are currently processing your order and we will email you with confirmation shortly.</p>
        <p>For your convenience you may want to save your order confirmation</p>
        <br>
        <h2>Delivery Details</h2>
        <hr>
        <h3>Delivery for</h3>
        <p>Name: <%= @purchase.name %></p>
        <p>Address: <%= @purchase.house_number %>, <%= @purchase.street_name %>, <%= @purchase.city%>, <%= @purchase.post_code%></p>
        <br>
        <h2>Payment Information</h2>
        <hr>
        <h3>Credit Card</h3>
        <p>Card Number: <%= @purchase.card_number %></p>
        <p>Expiry Date: <%= @purchase.expiry_date %></p>
      </div>
    <div class= "order-summary">
      <h2>Order Summary</h2>
      <hr>
      <p><%= cl_image_tag @purchase.vinyl.photo, height: 150, width: 150, crop: :fill  %></p>
      <p><%= @purchase.vinyl.name %></p>
      <p>£<%= @purchase.vinyl.price %></p>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
  <h1 class="text-center">User Reviews For <%= @user.first_name %></h1>
  <div class="container">
    <div class= "d-flex p-4 bg-light border-bottom align-items-center justify-content-between m-3">
      <div>
        <% @reviews.each do |review| %>
          <h2><strong>Buyer ID</strong></h2>
          <p><%= review.purchase.buyer_id %></p>
          <h2><strong>Content</strong></h2>
          <p><%= review.content %></p>
          <h2><strong>Rating</strong></h2>
          <p><%= review.rating %> stars</p>
          <hr>
        <% end %>
      </div>
    </div>
  </div>

app/views/reviews/new.html.erb
<h1 class="text-center">Rate your experience with <%= @purchase.vinyl.seller.first_name %> <%= @purchase.vinyl.seller.last_name %></h1>
<br>
<br>
<h2 class="text-center"><%= @purchase.vinyl.name %></h2>
<br>
<h1 class="text-center"><%= cl_image_tag @purchase.vinyl.photo, height: 300, width: 300 , crop: :fill  %></h1>
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= simple_form_for [@purchase, @review] do |f| %>
        <%= f.input :content, as: :text, label: "Leave your review below" %>
        <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
        <%= f.submit "Submit Review", class: "btn btn-primary m-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1 class="text-center">Thank you for your review</h1>
<hr>
<br>
<br>
<div class="container">
  <h1 class="text-center"><%= cl_image_tag @review.purchase.vinyl.photo, height: 300, width: 300 , crop: :fill  %></h1>
  <br>
  <h2 class="text-center"><%= @review.content %></h2>
  <br>
  <h2 class="text-center">
    <% @review.rating.times do %>
      <i class="fas fa-star" style="color: #FA2B57"></i>
    <% end %>
  <p><%= link_to "Browse More Vinyls", vinyls_path(@vinyl), class: 'btn btn-flat', style: 'color:white; margin: 15px;'%></p>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.2)), url('<%= image_path "banner.jpg" %>');">
  <div class="container">
    <h1 style= "font-size: 40px">Discover, buy, and sell incredible records</h1>
    <br>
    <%= render 'shared/search' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-copyright" style="color:#FA2B57"></i> True Vinyl 2019</i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.svg", class: "logo"%><span style="padding-left: 16px;">True Vinyl</span>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<!-- add in searchbar to nav?  <div class= "navbar-search">
    <%=  %>
  </div> -->


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Browse Vinyls", vinyls_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sell Vinyl", new_vinyl_path, class: 'nav-link', style: "margin-right: 15px;" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to current_user&.email, user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My Vinyls", vinyls_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My Purchases", user_purchases_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sell Vinyl", new_vinyl_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Account", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: vinyls_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="query" id="query" placeholder="Search artist, record or year" />
    <button name="button" type="submit" class="btn btn-flat">
      <!-- <i class="fas fa-search"></i> --> <i class="fas fa-compact-disc logo"></i> Search vinyls
    </button>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container-1">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Edit profile</h1>
      <%= simple_form_for [@user] do |f| %>
      <%= f.input :first_name, label: "First name" %>
      <%= f.input :last_name, label: "Last name"%>
      <%= f.input :email, label: "Email address" %>
      <%= f.input :address, label: "Address" %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>

app/views/users/show.html.erb
<div class="container" style="margin-top: 90px; margin-bottom: 20px">

  <div class="user">
    <div class="user-description">
      <h2>Hi, I'm <%= @user.first_name %></h2>
      <br>
      <h4>London</h4>
      <br>
      <p>I love music and would love to meet those who love it too! </p>
      <p>Get in touch if you have any question about any of my records on sale 🙏</p>
      <%= link_to "Update Profile", edit_user_path(current_user), class: 'btn btn-primary'%>
    </div>
    <div></div>
    <div class="profile-box">
      <div>
        <p><%= cl_image_tag(@user.photo.url, class: "avatar-bordered", :width => 100, :height => 100) %></p>
        <hr>
        <% if @user.reviews.count > 0 %>
          <% average_rating = 0 %>
          <% @user.reviews.each do |review| %>
              <% average_rating += review.rating %>
          <% end %>
          <% final = average_rating / @user.reviews.count %>
          <div style="color: #FA2B57">
          <% final.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          </div>
         <p><i class="far fa-check-circle"></i> <%= pluralize @user.reviews.count, "review" %></p>
          <% else %>
          <p><i class="far fa-check-circle"></i> No reviews yet</p>
          <% end %>

        <!-- @user.created_at -->
        <p><i class="far fa-calendar-alt"></i>    Selling since 2019</p>
      </div>
    </div>
  </div>

  <br>
  <div class="user-records-reviews">
    <div class="user-cards">
      <h3><%= @user.first_name %>'s Records</h3>
      <% @user.vinyls.each do |vinyl| %>
        <%= link_to vinyl_path(vinyl) do %>
          <div class="card-full">
            <div class="card-full-infos">
              <div>
                <h2><%= vinyl.name %></h2>
                <p><%= vinyl.artist %></p>
                <% if vinyl.sold? %>
                    <p>Sold</p>
                <% else %>
                  <p>Not sold</p>
                <% end %>
              </div>
              <h2 class="card-full-pricing">£ <%= vinyl.price %></h2>
            </div>
              <%= cl_image_tag vinyl.photo %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="reviews">
      <h3><%= @user.first_name %>'s Reviews</h3>
      <div style="color: #FA2B57">
      <% @user.reviews.each do |review| %>
        <p><%= review.content %></p>
        <% review.rating.times do %>
          <span class="fas fa-star"></span>
      <% end %>
      <hr>
      <% end %>
    </div>
  </div>

  </div>
</div>

app/views/users/show_vinyls.html.erb
<div class="container" style="margin-top: 90px; margin-bottom: 20px">
<h1 class="text-center">My Vinyls</h1>
  <div class="cards mt-4">
    <% @user.vinyls.each do |vinyl| %>
       <div class="card-full">
        <div class="card-full-infos">
          <div>
            <h2><%= vinyl.name %></h2>
            <p><%= vinyl.artist %></p>
            <% if vinyl.sold? %>
              <p>Sold</p>
            <% else %>
            <p>Not sold</p>
            <% end %>
          </div>
          <h2 class="card-full-pricing">£ <%= vinyl.price %></h2>
        </div>
          <%= link_to "Edit", edit_vinyl_path(vinyl), class: 'vinyl-button btn btn-primary' %>
          <%= link_to "Delete", vinyl_path(vinyl), method: :delete, class: 'vinyl-button-delete btn btn-primary' %>
          <%= link_to vinyl_path(vinyl) do %>
            <%= cl_image_tag vinyl.photo, height: 350, width: 350, crop: :fill %>
            <% end %>
      </div>

    <% end %>
  </div>
</div>

app/views/vinyls/show.html.erb
<div class="container" style="margin-top: 90px; margin-bottom: 20px">

  <div class="vinyl">

    <div class= "vinyl-image">
      <% if @vinyl.photo.nil? %>
        NO IMAGE
      <% else %>
        <%= cl_image_tag @vinyl.photo, height: 300, width: 300, crop: :fill %>
      <% end %>
    <% if @vinyl.media_link.length > 2 %>
        <iframe src="https://open.spotify.com/embed/album/<%= @vinyl.media_link.chars.last(22).join %>" frameborder="0" allowtransparency="true" height="80" allow="encrypted-media" style="margin-top:10px;"></iframe>
    <% end %>
    </div>

    <div class="vinyl-description">


      <h1><%= @vinyl.name %></h1>
      <h2><%= @vinyl.artist %></h2>

      <div style="display: grid; grid-template-columns: 1fr 1fr 1fr;  grid-gap: 8px; line-height: 1em; padding-bottom: 5px; ">
        <div style="border-left: 1px solid grey; padding-left: 8px; justify-content:center; ">
          <p style="color: light-grey;"><strong>Year</strong></p>
          <p><%= @vinyl.year %></p>
        </div>
        <div style="border-left: 1px solid grey; padding-left: 8px;">
          <p style="color: light-grey;"><strong>Genre</strong></p>
          <p><%= @vinyl.genre %></p>
        </div>
        <div style="border-left: 1px solid grey; padding-left: 8px;">
          <p style="color: light-grey;"><strong>Condition</strong></p>
          <p><%= @vinyl.condition %></p>
        </div>

      </div>

      <p><%= @vinyl.description %></p>

      <% if policy(@vinyl).edit? %>
        <%= link_to "Edit", edit_vinyl_path(@vinyl), class: 'btn btn-warning'%>
      <% end %>
    </div>

    <div class="profile-box">
      <div>
        <h2 style="color: #FA2B57"><strong>£<%= @vinyl.price %></strong></h2>
        <% if @vinyl.sold? %>
          <button type="button" class="btn btn-secondary" disabled>Already sold</button>
          <% else %>
          <%= link_to "buy now", order_vinyl_path(@vinyl), class: 'btn btn-danger', style: "width: 80%;" %>
        <% end %>
      </div>
      <div>
        <hr>
      </div>
      <div>
        <%= link_to user_path(@vinyl.seller) do %>

        <% if @vinyl.photo.nil? %>
          NO IMAGE
        <% else %>
          <p><%= cl_image_tag @vinyl.seller.photo, class: "avatar-user-page"%></p>
        <% end %>

        <h3> <%= @vinyl.seller.first_name %></h3>
        <% end %>
        <div style="color: #FA2B57">
        <% if @vinyl.seller.reviews.count > 0 %>
            <% average_rating = 0 %>
            <% @vinyl.seller.reviews.each do |review| %>
              <% average_rating += review.rating %>
            <% end %>
            <% final = average_rating / @vinyl.seller.reviews.count %>
            <div style="color: #FA2B57">
              <% final.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            </div>
          </div>
          <p><i class="far fa-check-circle"></i> <%= pluralize @vinyl.seller.reviews.count, "review" %></p>
          <% else %>
          <p><i class="far fa-check-circle"></i> No reviews yet</p>
            <% end %>
        <p><i class="far fa-calendar-alt"></i>    Selling since 2019</p>
        </div>
      </div>
    </div>

   <br>
  <h3>Other items for sale by <%= @vinyl.seller.first_name %> </h3>
  <br>

  </div>
  <div style="width: 100%; display: flex;flex-direction: row;justify-content: left;flex-wrap: wrap;">
   <% @user_vinyls.each do |vinyl| %>

     <%= link_to vinyl_path(vinyl) do %>
       <div class="card-full">
         <div class="card-full-infos">
           <div>
             <h2><%= vinyl.name %></h2>
             <p><%= vinyl.artist %></p>
             <% if vinyl.sold? %>
                 <p>Sold</p>
             <% else %>
               <p>Not sold</p>
             <% end %>
           </div>
           <h2 class="card-full-pricing">£ <%= '%.2f' % vinyl.price %></h2>
         </div>
           <%= cl_image_tag vinyl.photo %>
       </div>
     <% end %>
   <% end %>

  </div>